a = int(input("Enter 1st number: "))
b = int(input("Enter 2nd number: "))
print("And Operator:", a & b)
print("Or Operator:", a | b)
print("Not Operator:", ~a)
print("XOr Operator:", (a ^ b))
print("Left shift", a << b)
print("Right shift", a >> b)
